#!/usr/bin/env python3
"""Offline constrained-GRPO update from recorded candidate trajectory groups.

Rollout JSONL schema (one prompt/context group per line):
  feature_file: NPZ containing acoustic[T,D_a], semantic[T,D_s]
  candidates: [{actions:[T], old_log_probs:[T], reference_log_probs:[T],
                reward:float, safety_cost:float}, ...]

Rollouts must be generated by the frozen pre-update policy. This script refuses
single-candidate groups because GRPO would have no within-group comparison.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

import numpy as np
import torch

from bootstrap import ROOT
from tfd.duplex_policy.actions import Action
from tfd.duplex_policy.grpo import clipped_grpo_loss
from tfd.duplex_policy.rewards import ConstrainedGRPOState, group_relative_advantages
from tfd.duplex_policy.trainer import load_checkpoint, save_checkpoint


def _action_ids(values: list) -> list[int]:
    return [int(value) if isinstance(value, int) else Action.from_label(value).value for value in values]


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--checkpoint", type=Path, required=True)
    parser.add_argument("--rollouts", type=Path, required=True)
    parser.add_argument("--output", type=Path, default=ROOT / "outputs/duplex_policy_v3/grpo.pt")
    parser.add_argument("--device", default="cuda" if torch.cuda.is_available() else "cpu")
    parser.add_argument("--epochs", type=int, default=1)
    parser.add_argument("--lr", type=float, default=1e-5)
    parser.add_argument("--cost-budget", type=float, default=0.05)
    parser.add_argument("--dual-lr", type=float, default=0.02)
    args = parser.parse_args()
    rows = [json.loads(line) for line in args.rollouts.read_text(encoding="utf-8").splitlines() if line.strip()]
    if not rows:
        raise ValueError("rollout file is empty")
    model, source = load_checkpoint(args.checkpoint, map_location=args.device)
    model.to(args.device).train()
    optimizer = torch.optim.AdamW(model.parameters(), lr=args.lr)
    dual = ConstrainedGRPOState(cost_budget=args.cost_budget, dual_lr=args.dual_lr)
    history = []
    for epoch in range(1, args.epochs + 1):
        totals = {"loss": 0.0, "groups": 0}
        for row in rows:
            candidates = row["candidates"]
            if len(candidates) < 2:
                raise ValueError("every GRPO group needs at least two candidates")
            feature_path = Path(row["feature_file"])
            if not feature_path.is_absolute():
                feature_path = (args.rollouts.parent / feature_path).resolve()
            with np.load(feature_path, allow_pickle=False) as payload:
                acoustic = torch.tensor(payload["acoustic"], dtype=torch.float32, device=args.device).unsqueeze(0)
                semantic = torch.tensor(payload["semantic"], dtype=torch.float32, device=args.device).unsqueeze(0)
            valid = torch.ones(acoustic.shape[:2], dtype=torch.bool, device=args.device)
            output = model(acoustic, semantic, valid)
            log_probs = output.action_logits.log_softmax(-1).squeeze(0)
            rewards = torch.tensor([[float(c["reward"]) for c in candidates]], device=args.device)
            costs = torch.tensor([[float(c["safety_cost"]) for c in candidates]], device=args.device)
            group_adv = group_relative_advantages(
                rewards, costs, lagrange_multiplier=dual.lagrange_multiplier
            ).squeeze(0)
            candidate_new, candidate_old, candidate_ref, candidate_adv = [], [], [], []
            for index, candidate in enumerate(candidates):
                actions = torch.tensor(_action_ids(candidate["actions"]), device=args.device)
                if len(actions) != len(log_probs):
                    raise ValueError("candidate actions must align with feature frames")
                candidate_new.append(log_probs.gather(1, actions.unsqueeze(1)).squeeze(1))
                old = torch.tensor(candidate["old_log_probs"], dtype=torch.float32, device=args.device)
                ref = torch.tensor(candidate.get("reference_log_probs", candidate["old_log_probs"]), dtype=torch.float32, device=args.device)
                if len(old) != len(actions) or len(ref) != len(actions):
                    raise ValueError("logged probabilities must align with actions")
                candidate_old.append(old)
                candidate_ref.append(ref)
                candidate_adv.append(torch.full_like(old, group_adv[index]))
            new = torch.stack(candidate_new)
            old = torch.stack(candidate_old)
            ref = torch.stack(candidate_ref)
            advantages = torch.stack(candidate_adv)
            mask = torch.ones_like(new, dtype=torch.bool)
            loss, parts = clipped_grpo_loss(
                new, old, advantages, mask, reference_log_probs=ref
            )
            optimizer.zero_grad(set_to_none=True)
            loss.backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
            optimizer.step()
            dual.update(costs)
            totals["loss"] += float(loss.detach().cpu())
            totals["groups"] += 1
        record = {
            "epoch": epoch,
            "loss": totals["loss"] / totals["groups"],
            "lagrange_multiplier": dual.lagrange_multiplier,
            "cost_budget": dual.cost_budget,
        }
        history.append(record)
        print(json.dumps(record))
    save_checkpoint(
        args.output,
        model=model,
        optimizer=optimizer,
        epoch=int(source.get("epoch", 0)) + args.epochs,
        metrics={"grpo_loss": history[-1]["loss"], "lagrange_multiplier": dual.lagrange_multiplier},
    )
    report_path = args.output.with_suffix(".report.json")
    report_path.write_text(
        json.dumps({"format": "tfd-star-constrained-grpo-v3", "history": history}, indent=2),
        encoding="utf-8",
    )
    print(f"[ok] constrained GRPO checkpoint -> {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
